import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AppModule } from './app.module';
import { toNodeHandler } from 'better-auth/node';
import { auth } from './auth';
import * as express from 'express';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

async function bootstrap() {
  // Disable default NestJS body parser so Better Auth can process raw requests
  const app = await NestFactory.create(AppModule, { bodyParser: false });

  // Reflect the requesting origin back — required for cross-origin requests
  // with credentials (cookies) from any team member's machine.
  app.enableCors({
    origin: (origin, callback) => callback(null, origin ?? true),
    credentials: true,
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS',
    allowedHeaders: 'Content-Type, Accept, Authorization',
  });

  // Enable global validation for all DTOs
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));

  const expressApp = app.getHttpAdapter().getInstance();

  // Mount Better Auth's handler BEFORE body-parsers
  expressApp.all('/api/auth/{*any}', toNodeHandler(auth));

  // Re-enable body-parsers for NestJS routes
  expressApp.use(express.json());
  expressApp.use(express.urlencoded({ extended: true }));

  // Setup Swagger API documentation
  const config = new DocumentBuilder()
    .setTitle('QueenPM API')
    .setDescription('The backend API documentation for QueenPM Project Management system')
    .setVersion('1.0')
    .addCookieAuth('better-auth.session_token', {
      type: 'apiKey',
      in: 'cookie',
      name: 'better-auth.session_token',
      description: 'Session cookie token generated by Better Auth',
    })
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api/docs', app, document);

  await app.listen(process.env.PORT ?? 3001);
}
bootstrap();

