import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AppModule } from './app.module';
import { toNodeHandler } from 'better-auth/node';
import { auth } from './auth';
import * as express from 'express';
// Load Swagger dynamically to avoid startup failures when the package is missing
// (some deployments may not include @nestjs/swagger). We require it at runtime
// inside a try/catch so the app can still start without docs.

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bodyParser: false });
  app.setGlobalPrefix('api');

  // Reflect the requesting origin back — required for cross-origin requests
  // with credentials (cookies) from any team member's machine.
  app.enableCors({
    origin: (origin, callback) => callback(null, origin ?? true),
    credentials: true,
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS',
    allowedHeaders: 'Content-Type, Accept, Authorization',
  });

  // Enable global validation for all DTOs
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));

  const expressApp = app.getHttpAdapter().getInstance();

  // Mount Better Auth's handler BEFORE body-parsers, but let custom NestJS AuthController handle custom endpoints
  const authHandler = toNodeHandler(auth);
  const customAuthPaths = [
    '/api/auth/sign-in',
    '/api/auth/sign-up',
    '/api/auth/sign-out',
    '/api/auth/session',
    '/api/auth/me',
  ];
  expressApp.use('/api/auth', (req, res, next) => {
    const fullPath = req.originalUrl.split('?')[0];
    if (customAuthPaths.includes(fullPath)) {
      return next();
    }
    return authHandler(req, res);
  });

  // Re-enable body-parsers for NestJS routes
  expressApp.use(express.json());
  expressApp.use(express.urlencoded({ extended: true }));

  // Setup Swagger API documentation (loaded dynamically)
  try {
    const swag = await import('@nestjs/swagger');
    const { SwaggerModule, DocumentBuilder } = swag;
    const config = new DocumentBuilder()
      .setTitle('QueenPM API')
      .setDescription('The backend API documentation for QueenPM Project Management system')
      .setVersion('1.0')
      .addCookieAuth('better-auth.session_token', {
        type: 'apiKey',
        in: 'cookie',
        name: 'better-auth.session_token',
        description: 'Session cookie token generated by Better Auth',
      })
      .build();
    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('api/docs', app, document);
  } catch (e) {
    // If @nestjs/swagger isn't installed or fails to load, continue without docs
    // This avoids crashing the app in environments where docs aren't needed.
    // Log minimal warning so operators can take action if desired.
    // eslint-disable-next-line no-console
    console.warn('Swagger not available; skipping API docs setup.');
  }

  await app.listen(process.env.PORT ?? 3001);
}
bootstrap();

