/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SprintConfigRouteImport } from './routes/sprint-config'
import { Route as SprintRouteImport } from './routes/sprint'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChannelsConfigRouteImport } from './routes/channels-config'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintConfigRoute = SprintConfigRouteImport.update({
  id: '/sprint-config',
  path: '/sprint-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintRoute = SprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsConfigRoute = ChannelsConfigRouteImport.update({
  id: '/channels-config',
  path: '/channels-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/channels': typeof ChannelsRoute
  '/channels-config': typeof ChannelsConfigRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/sprint': typeof SprintRoute
  '/sprint-config': typeof SprintConfigRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/channels': typeof ChannelsRoute
  '/channels-config': typeof ChannelsConfigRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/sprint': typeof SprintRoute
  '/sprint-config': typeof SprintConfigRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/channels': typeof ChannelsRoute
  '/channels-config': typeof ChannelsConfigRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/sprint': typeof SprintRoute
  '/sprint-config': typeof SprintConfigRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/channels'
    | '/channels-config'
    | '/login'
    | '/projects'
    | '/sprint'
    | '/sprint-config'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/channels'
    | '/channels-config'
    | '/login'
    | '/projects'
    | '/sprint'
    | '/sprint-config'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/channels'
    | '/channels-config'
    | '/login'
    | '/projects'
    | '/sprint'
    | '/sprint-config'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ChannelsRoute: typeof ChannelsRoute
  ChannelsConfigRoute: typeof ChannelsConfigRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  SprintRoute: typeof SprintRoute
  SprintConfigRoute: typeof SprintConfigRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint-config': {
      id: '/sprint-config'
      path: '/sprint-config'
      fullPath: '/sprint-config'
      preLoaderRoute: typeof SprintConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint': {
      id: '/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof SprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels-config': {
      id: '/channels-config'
      path: '/channels-config'
      fullPath: '/channels-config'
      preLoaderRoute: typeof ChannelsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ChannelsRoute: ChannelsRoute,
  ChannelsConfigRoute: ChannelsConfigRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  SprintRoute: SprintRoute,
  SprintConfigRoute: SprintConfigRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
